spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

---
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://127.0.0.2:3306/em?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1

---
spring:
  profiles: development

  datasource:
    url: jdbc:mysql://172.16.30.126:3306/em?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ems
    password: 123456aA@

---
spring:
  profiles: production

  datasource:
    url: jdbc:mysql://10.60.88.22:9999/em?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ems
    password: 123456aA@
